export type CultureCounts = {
  rumahAdat: number;
  tarian: number;
  musik: number;
  kuliner: number;
  cerita: number;
  pakaian: number;
  tradisi: number;
  senjata: number;
  flora: number;
  fauna: number;
};

export type Province = {
  id: string;
  name: string;
  island: "Sumatera" | "Jawa" | "Kalimantan" | "Sulawesi" | "Bali & Nusa Tenggara" | "Maluku" | "Papua";
  lat: number;
  lng: number;
  emoji: string;
  capital: string;
  rumahAdat: string;
  tarian: string;
  makanan: string;
  alatMusik: string;
  pakaianAdat: string;
  tradisi: string;
  senjataTradisional: string;
  flora: string;
  floraLatin: string;
  floraEnglish?: string;
  fauna: string;
  faunaLatin: string;
  faunaEnglish?: string;
  cerita: string;
  counts: CultureCounts;
};

export const provinces: Province[] = [
  {
    id: "aceh",
    name: "Aceh",
    island: "Sumatera",
    lat: 4.03,
    lng: 96.63,
    emoji: "🕌",
    capital: "Banda Aceh",
    rumahAdat: "Rumoh Aceh",
    tarian: "Tari Saman",
    makanan: "Mi Aceh, Gulai Bebek dan Meuseukat",
    alatMusik: "Arbab, Bereguh dan Calempong",
    pakaianAdat: "Ulee Balang",
    tradisi: "Seumeuleung Raja, Gegedem dan Geudeu-Geudeu",
    senjataTradisional: "Rintjong Aceh",
    flora: "Bungong Jeumpa, Cempaka Wangi, Cempaka Kuning, Cepaga (Bugis), Campaka Mariri (Sulawesi Utara), Campaga (Minangkabau)",
    floraLatin: "Magnolia Champaca",
    floraEnglish: "Yellow Champaca",
    fauna: "Cempala Kuning/ Kucica Ekor Kuning, Cicem Pala Kuneng",
    faunaLatin: "Trichixos Pyrropygus",
    faunaEnglish: "Rufous-Tailed Shama",
    cerita: "Serambi Mekkah dengan Tari Saman yang diakui UNESCO!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "sumut",
    name: "Sumatera Utara",
    island: "Sumatera",
    lat: 1.83,
    lng: 98.75,
    emoji: "🏞️",
    capital: "Medan",
    rumahAdat: "Rumah Bolon",
    tarian: "Tortor",
    makanan: "Soto Batak, Arsik, dan Mie Gomak",
    alatMusik: "Ole-ole, Balobat dan Odap",
    pakaianAdat: "Pakaian Adat Ulos",
    tradisi: "Ulos dan tarian Tortor",
    senjataTradisional: "Piso Tumbuk Lada, Piso Gaja Dompak dan Tongkat Tunggal Panaluan",
    flora: "Bunga Kenanga, Sapalen (Baru), Kananga (Sunda), Wanggulita (Gorontalo), Sandat Wangsa (Madura), Inangai (Minangkabau)",
    floraLatin: "Cananga Odorata",
    floraEnglish: "Ylang-Ylang",
    fauna: "Beo Nias/Ciong, Tiong, Mamiang, Tiong Emas",
    faunaLatin: "Gracula Religiosa Robusta",
    faunaEnglish: "Common Hill Myna",
    cerita: "Danau Toba adalah danau vulkanik terbesar di dunia!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "sumbar",
    name: "Sumatera Barat",
    island: "Sumatera",
    lat: -1.33,
    lng: 100.24,
    emoji: "🏠",
    capital: "Padang",
    rumahAdat: "Rumah Gadang",
    tarian: "Tari Piring dan Tari Payung",
    makanan: "Rendang, Sate Padang dan Bubur Kampiun",
    alatMusik: "Saluang",
    pakaianAdat: "Pakaian Adat Bundo Kanduang",
    tradisi: "Pakaian adat Bundo Kanduang dan Karih, Tari Piring, dan Tari Payung",
    senjataTradisional: "Karih",
    flora: "Pohon Andalas, Bebesaran, Hole Tanduk (Batak), Andaleh (Minangkabau), Kertau (Sunda)",
    floraLatin: "Morus Macroura",
    floraEnglish: "Sumatran Mulberry",
    fauna: "Kuau Raja, Kuang",
    faunaLatin: "Argusianus Argus",
    faunaEnglish: "Great Argus",
    cerita: "Atap Rumah Gadang berbentuk tanduk kerbau yang megah!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "riau",
    name: "Riau",
    island: "Sumatera",
    lat: 0.9,
    lng: 101.93,
    emoji: "🌴",
    capital: "Pekanbaru",
    rumahAdat: "Rumah Melayu Riau",
    tarian: "Tari Mak Yong, Tari Zapin Api dan Tarian Makan Sirih",
    makanan: "Sup Tunjang, Gulai Ikan Patin dan Lakse Kuah",
    alatMusik: "Rebab, Gendang dan Tetawak",
    pakaianAdat: "Baju Teluk Belanga, Baju Cekak Musang dan Tenun Songket Riau",
    tradisi: "Pacu Jalur, Randai Kuantan dan Silat Perisai",
    senjataTradisional: "Klewang, Pedang Jenawi dan Keris Riau",
    flora: "Pohon Palem Nibung",
    floraLatin: "Oncosperma Tigillarium",
    floraEnglish: "Nibong Palm",
    fauna: "Serindit Melayu/ Sindit, Seindit",
    faunaLatin: "Loriculus Galgulus",
    faunaEnglish: "Blue-Crowned Hanging Parrot",
    cerita: "Negeri Melayu yang kaya akan tradisi Gurindam 12!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "kepri",
    name: "Kepulauan Riau",
    island: "Sumatera",
    lat: 1.76,
    lng: 106.22,
    emoji: "⚓",
    capital: "Tanjung Pinang",
    rumahAdat: "Rumah Belah Bubung, Limas Potong dan Balai Salaso Jatuh",
    tarian: "Tari Zapin, Tari Sekapur Sirih, dan Tari Makyong",
    makanan: "Gonggong, Mie Lendir dan Nasi Lemak",
    alatMusik: "Nafiri, Gambus Melayu dan Akordeon/Kordeon",
    pakaianAdat: "Baju Teluk Belanga dan Kebaya Labuh",
    tradisi: "Rumah Lontiok, Zapin Api dan Tepuk Tepung Tawar",
    senjataTradisional: "Pedang Janawi, Klewang dan Beladau",
    flora: "Tanaman Sirih",
    floraLatin: "Piper Betle",
    floraEnglish: "Betel",
    fauna: "Ikan Kakap Merah",
    faunaLatin: "Lutjanus Argentimaculatus",
    faunaEnglish: "Red Snapper",
    cerita: "Provinsi seribu pulau indah di perbatasan Nusantara!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "jambi",
    name: "Jambi",
    island: "Sumatera",
    lat: -1.75,
    lng: 102.82,
    emoji: "🌿",
    capital: "Jambi",
    rumahAdat: "Rumah Panggung Kajang Lako",
    tarian: "Tari Sekapur Sirih, Tari Rentak Besapih dan Tari Tauh",
    makanan: "Gulai Ikan Patin dan Nasi Gemuk",
    alatMusik: "Cangor, Serangko, dan Gendang Melayu",
    pakaianAdat: "Baju Kurung Tanggung",
    tradisi: "Nasi Gemuk",
    senjataTradisional: "Badik Tumbuk Lada, Keris Siginjai dan Tombak Jambi Perdang bermata dobel",
    flora: "Pohon Pinang Merah",
    floraLatin: "Cyrtostachys Renda",
    floraEnglish: "Lipstick Palm (Malaya Sealing Wax Palm)",
    fauna: "Harimau Sumatera",
    faunaLatin: "Panthera Tigris Sumatrae",
    faunaEnglish: "Sumatran Tiger",
    cerita: "Kompleks Candi Muaro Jambi adalah situs bata terluas di Asia Tenggara!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "sumsel",
    name: "Sumatera Selatan",
    island: "Sumatera",
    lat: -3.28,
    lng: 104.14,
    emoji: "🌉",
    capital: "Palembang",
    rumahAdat: "Rumah Limas",
    tarian: "Tari Tanggai dan Dulmuluk",
    makanan: "Pempek, Tekwan, Pindang Patin",
    alatMusik: "Gandang dan Gong",
    pakaianAdat: "Pakaian Adat Aesan Gede dan Aesan Pak Sangko",
    tradisi: "Songket Palembang, Tari Tanggai dan Syair Dulmuluk",
    senjataTradisional: "Trisula dan Keris Sumsel",
    flora: "Pohon Buah Duku",
    floraLatin: "Lansium Domesticum",
    floraEnglish: "Langsat",
    fauna: "Ikan Belida",
    faunaLatin: "Chitala Lopis",
    faunaEnglish: "Knifefish/Featherback",
    cerita: "Pusat Kerajaan Sriwijaya yang terkenal di seluruh Asia Ancient!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "bengkulu",
    name: "Bengkulu",
    island: "Sumatera",
    lat: -3.9,
    lng: 102.41,
    emoji: "🌺",
    capital: "Bengkulu",
    rumahAdat: "Rumah Bubungan Lima",
    tarian: "Tari Andun, Tari Bidadari Teminang Anak dan Tari Tabot",
    makanan: "Pendap, Kue Tat dan Bagar Hiu",
    alatMusik: "Doll/Doli, Gendang Panjang dan Redap",
    pakaianAdat: "Pakaian Adat Rejang Lebong",
    tradisi: "Tabut",
    senjataTradisional: "Rudus, Rambai Ayam dan Keris Terapang",
    flora: "Bunga Bangkai",
    floraLatin: "Rafflesia Arnoldii",
    floraEnglish: "Corpse Flower",
    fauna: "Beruang Madu",
    faunaLatin: "Helarctos malayanus",
    faunaEnglish: "Sun Bear",
    cerita: "Habitat asli bunga raksasa langka Rafflesia Arnoldii!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "lampung",
    name: "Lampung",
    island: "Sumatera",
    lat: -4.95,
    lng: 104.94,
    emoji: "🐘",
    capital: "Bandar Lampung",
    rumahAdat: "Nuwo Sesat, Lamban Pesagi dan Mahanyuk'an",
    tarian: "Tari Bedana, Tari Topeng dan Tari Melinting",
    makanan: "Seruit, Gulai Taboh dan Tempoyak, Geguduh",
    alatMusik: "Gambus Lampung, Bende dan Kolintang",
    pakaianAdat: "Pakaian Adat Tulang Bawang, Pepadun dan Saibatin",
    tradisi: "Gamolan, Gambus dan Kompang",
    senjataTradisional: "Terapang, Badik Lampung, dan Taji Ayam",
    flora: "Bunga Ashar",
    floraLatin: "Mirabilis Jalapa L",
    floraEnglish: "Four O'clock Flower",
    fauna: "Gajah Sumatera",
    faunaLatin: "Elephas Maximus Sumatranus",
    faunaEnglish: "Sumatran Elephant",
    cerita: "Rumah perlindungan gajah Sumatra di Taman Nasional Way Kambas!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "babel",
    name: "Kepulauan Bangka Belitung",
    island: "Sumatera",
    lat: -2.65,
    lng: 106.99,
    emoji: "⛱️",
    capital: "Pangkal Pinang",
    rumahAdat: "Rumah Panggung, Rumah Limas dan Rumah Rakit",
    tarian: "Tari Campak dan Tari Zapin",
    makanan: "Lempah Kuning, Kemplang Belacan dan Mie Bangka",
    alatMusik: "Gendang Melayu, Rebana dan Suling",
    pakaianAdat: "Pakaian Adat Paksian",
    tradisi: "Dambus, Campak Dalung dan Adat Maras Taun",
    senjataTradisional: "Parang Badau, Kedik dan Siwar Panjang",
    flora: "Pohon Nagasari/ Nyatoh",
    floraLatin: "Palaquium Rostratum",
    floraEnglish: "Nyatoh",
    fauna: "Mentilin",
    faunaLatin: "Tarsius bancanus",
    faunaEnglish: "Horsfield's Tarsier",
    cerita: "Pantai batu granit raksasa yang menjadi tempat Laskar Pelangi!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "dkijakarta",
    name: "DKI Jakarta",
    island: "Jawa",
    lat: -5.79,
    lng: 106.68,
    emoji: "🏙️",
    capital: "Jakarta",
    rumahAdat: "Rumah Adat Betawi",
    tarian: "Tari Belenggo dan Tari Lenggong Nyai",
    makanan: "Kerak Telor, Roti Buaya dan Soto Betawi",
    alatMusik: "Gambang Kromong, Keroncong Tugu dan Tanjidor",
    pakaianAdat: "Pakaian Adat Kebaya Encim dan Sadariah",
    tradisi: "Ondel-ondel, Tanjidor dan Lenong",
    senjataTradisional: "Golok Betawi, Badik Cangkingan dan Senjata Tradisional Cunrik",
    flora: "Salak Condet",
    floraLatin: "Salacca Edulis",
    floraEnglish: "Snake Fruit",
    fauna: "Elang Bondol",
    faunaLatin: "Haliastur Indus",
    faunaEnglish: "Brahminy Kite",
    cerita: "Ibu kota bersejarah dengan ikon Monumen Nasional berlapis emas!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "jabar",
    name: "Jawa Barat",
    island: "Jawa",
    lat: -6.81,
    lng: 107.61,
    emoji: "🎋",
    capital: "Bandung",
    rumahAdat: "Rumah Julung Ngapak, Rumah Jolopong dan Rumah Capit Gunting",
    tarian: "Tari Jaipong, Tari Merak dan Topeng Cirebon",
    makanan: "Nasi Timbel, Karedok dan Tahu Sumedang",
    alatMusik: "Angklung, Gamelang Degung dan Tarawangsa",
    pakaianAdat: "Pakaian Adat Bedahan dan Kebaya Sunda",
    tradisi: "Jaipong, Topeng Cirebon dan Sisingaan",
    senjataTradisional: "Kujang",
    flora: "Gandaria",
    floraLatin: "Bouea Macrophylla Griffith",
    floraEnglish: "Plum Mango",
    fauna: "Macan Tutul Jawa",
    faunaLatin: "Panthera pardus melas",
    faunaEnglish: "Java Leopard",
    cerita: "Alat musik bambu Angklung ciptaan tanah Pasundan telah mendunia!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "banten",
    name: "Banten",
    island: "Jawa",
    lat: -6.41,
    lng: 105.94,
    emoji: "🎭",
    capital: "Serang",
    rumahAdat: "Rumah Adat Banten Sulah Nyanda",
    tarian: "Tari Cokek, Tari Jaipong dan Tari Debus",
    makanan: "Sate Bandeng, Rabeg dan Gerem Asem",
    alatMusik: "Angklung Gubrag, Bambu Jitak dan Kacapi",
    pakaianAdat: "Baju Pangsi Banten, Pakaian Suku Baduy Dalam dan Pakaian Suku Baduy Luar",
    tradisi: "Seren Taun",
    senjataTradisional: "Bedog, Golok Ciomas dan Golok Sulangkar",
    flora: "Kokoleceran",
    floraLatin: "Vatica Bantamensis",
    floraEnglish: "Banten Vatica",
    fauna: "Badak Jawa/ Badak Bercula Satu",
    faunaLatin: "Rhinoceros sondaicus",
    faunaEnglish: "Javan Rhino",
    cerita: "Taman Nasional Ujung Kulon adalah suaka badak bercula satu!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "jateng",
    name: "Jawa Tengah",
    island: "Jawa",
    lat: -6.97,
    lng: 110.12,
    emoji: "🏯",
    capital: "Semarang",
    rumahAdat: "Rumah Adat Limasan, Rumah Joglo Pangrawit dan Rumah Joglo Mangkurat",
    tarian: "Tari Gambyong, Tari Bedhaya dan Tari Tayub",
    makanan: "Lumpia Semarang, Bandeng Presto dan Soto Kudus",
    alatMusik: "Gamelan Jawa, Angklung Banyumasan dan Slenthem",
    pakaianAdat: "Pakaian Adat Kebaya Jawa",
    tradisi: "Wayang Kulit, Batik Solo/Pekalongan dan Seni ukir",
    senjataTradisional: "Keris, Tombak dan Wedhung",
    flora: "Bunga Kantil",
    floraLatin: "Michelia Alba",
    floraEnglish: "White Champaca",
    fauna: "Burung Kepondang Emas",
    faunaLatin: "Oriolus Chinensis",
    faunaEnglish: "Black-Naped Oriole",
    cerita: "Candi Borobudur adalah candi Buddha terbesar di planet Bumi!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "diy",
    name: "Daerah Istimewa Yogyakarta",
    island: "Jawa",
    lat: -7.87,
    lng: 110.42,
    emoji: "👑",
    capital: "Yogyakarta",
    rumahAdat: "Rumah Adat Joglo",
    tarian: "Tari Serimpi, Tari Beksan Lawung Ageng dan Tari Golek Ayun-ayun",
    makanan: "Gudeg, Soto Daging Khas Yogyakarta dan Jadah Manten",
    alatMusik: "Gamelan, Dhodhog, dan Thunthung,",
    pakaianAdat: "Kebaya, Beskap dan Blangkon",
    tradisi: "Sumbu FIlosofi Yogyakarta, Tradisi Grebeg dan Tradisi Labuhan",
    senjataTradisional: "Keris",
    flora: "Pohon Burahol/Kepel",
    floraLatin: "Stelechocarpus Burahol",
    floraEnglish: "Kepel Apple",
    fauna: "Burung Perkutut",
    faunaLatin: "Geopelia Striata",
    faunaEnglish: "Barred Ground Dove",
    cerita: "Kota budaya bersejarah dengan tradisi Keraton yang lestari!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "jatim",
    name: "Jawa Timur",
    island: "Jawa",
    lat: -6.91,
    lng: 113.58,
    emoji: "🌋",
    capital: "Surabaya",
    rumahAdat: "Rumah Osing, Rumah Tengger dan Rumah Tanean Lanjhang",
    tarian: "Reog Ponorogo, Tari Jaranan Buto dan Topeng Malangan",
    makanan: "Rawon, Soto Lamongan dan Rujak Cingur",
    alatMusik: "Gamelan Jawa Timur, Angklung Caruk dan Terompet Reog",
    pakaianAdat: "Pakaian Adat Pesa'an, Kebaya Rancongan dan Baju Cak-Ning Surabaya",
    tradisi: "Wayang Topeng Malang, Reog Ponorogo dan Jaran Kencak",
    senjataTradisional: "Keris, Clurit dan Kudi",
    flora: "Bunga Sedap Malam",
    floraLatin: "Polyanthes Tuberosa",
    floraEnglish: "Tuberose",
    fauna: "Ayam Bekisar",
    faunaLatin: "Gallus Varius",
    faunaEnglish: "Green Junglefowl, Javan Junglefowl, Forktail",
    cerita: "Kesenian Reog Ponorogo menampilkan topeng kepala singa raksasa!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "bali",
    name: "Bali",
    island: "Bali & Nusa Tenggara",
    lat: -8.46,
    lng: 115.07,
    emoji: "🔥",
    capital: "Denpasar",
    rumahAdat: "Rumah Bali",
    tarian: "Tari Pendet, Tari Topeng dan Tari Kecak",
    makanan: "Sate Lilit, Babi Guling dan Ayam Betutu",
    alatMusik: "Gamelan, Jegog dan Genggong",
    pakaianAdat: "Payas Agung, Payas Madya dan Payas Alit",
    tradisi: "Ngaben, Melasti, Galungan",
    senjataTradisional: "Blakas",
    flora: "Pohon Majegau",
    floraLatin: "Dysoxylum Densiflorum",
    floraEnglish: "Jasmine Wood",
    fauna: "Burung Jalak Bali",
    faunaLatin: "Leucopsar Rothschildi",
    faunaEnglish: "Bali Myna",
    cerita: "Pulau Dewata yang terkenal dengan Tari Kecak & keindahan pantai!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "ntb",
    name: "Nusa Tenggara Barat",
    island: "Bali & Nusa Tenggara",
    lat: -8.59,
    lng: 117.58,
    emoji: "🏖️",
    capital: "Mataram",
    rumahAdat: "Bale Lumbung dan Berugaq Sekenam",
    tarian: "Tari Oncer, Tari Mpaa Lenggogo dan Tari Sanggulu",
    makanan: "Ayam Taliwang, Sate Bulayak dan Uta Palumara",
    alatMusik: "Gendang Beleq, Palompong dan Pereret",
    pakaianAdat: "Baju Pegon, Lambung dan Rimpu",
    tradisi: "Tarian adat Mpaa Lenggogo, Tradisi Peresean dan Perang Topat",
    senjataTradisional: "Keris, Klewang dan Tulup",
    flora: "Pohon Ajan Kelicung",
    floraLatin: "Diospyros Macrophylla",
    floraEnglish: "Ajan Kelicung",
    fauna: "Rusa Timor",
    faunaLatin: "Cervus Timorensis",
    faunaEnglish: "Timor Deer",
    cerita: "Rumah Gunung Rinjani dan tradisi Pacuan Kuda Sumba!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "ntt",
    name: "Nusa Tenggara Timur",
    island: "Bali & Nusa Tenggara",
    lat: -9.39,
    lng: 122.06,
    emoji: "🐉",
    capital: "Kupang",
    rumahAdat: "Rumah Adat Mbaru Niang, Rumah Adat Musalaki dan Rumah Adat Sao Ngada",
    tarian: "Tari Perang, Tari Gareng Lameng dan Tari Tebe",
    makanan: "Katemak",
    alatMusik: "Sasando, Gendang dan Kompang",
    pakaianAdat: "Baju Sabu, Amarasi dan Ikat Patola",
    tradisi: "Tradisi tari Lendo dan Ritual khitan (Gareng Lameng)",
    senjataTradisional: "Hemola",
    flora: "Cendana",
    floraLatin: "Santalum Album",
    floraEnglish: "Indian Sandalwood",
    fauna: "Komodo/ Ora",
    faunaLatin: "Varanus Komodoensis",
    faunaEnglish: "Komodo Dragon",
    cerita: "Taman Nasional Komodo adalah satu-satunya habitat naga Komodo di dunia!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "kalbar",
    name: "Kalimantan Barat",
    island: "Kalimantan",
    lat: -0.49,
    lng: 111.4,
    emoji: "🌳",
    capital: "Pontianak",
    rumahAdat: "Rumah Panjang Radakng",
    tarian: "Tari Monong, Tari Kondan dan Tari Kinyah Uut Danum",
    makanan: "Bubur Pedas Sambas",
    alatMusik: "Silotong, Entebong, dan Keledik",
    pakaianAdat: "Pakaian Adat King Baba dan King Bibinge",
    tradisi: "Raja busana Dayak (King Baba, King Bibinge)",
    senjataTradisional: "Mandau, Pandat dan Tombak",
    flora: "Pohon Tengkawang Tungkul/ Meranti merah",
    floraLatin: "Shorea Spp",
    floraEnglish: "Illipe Nut / Red Meranti",
    fauna: "Burung Enggang Gading/Rangkong Gading",
    faunaLatin: "Rhinoplax Vigil",
    faunaEnglish: "Helmeted Hornbill",
    cerita: "Kota Pontianak dilalui tepat oleh garis katulistiwa lintang 0 derajat!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "kalteng",
    name: "Kalimantan Tengah",
    island: "Kalimantan",
    lat: -1.38,
    lng: 113.29,
    emoji: "🦧",
    capital: "Palangkaraya",
    rumahAdat: "Rumah Betang",
    tarian: "Tari Tambun Bungai, Kinyah Mandau Hatue dan Babukung",
    makanan: "Kalumpe, Sulur Keladi Katuk Telur dan Wadi",
    alatMusik: "Japeh, Garantung dan Gandang Manca",
    pakaianAdat: "Pakaian Adat Sangkarut",
    tradisi: "Patung Sapundu, Mandau dan Tiwaah",
    senjataTradisional: "Mandau dan Talawang",
    flora: "Pohon Tenggaring/Rambutan",
    floraLatin: "Nephelium Ramboutan-ake",
    floraEnglish: "Pulasan",
    fauna: "Burung Kuau Kerdil Kalimantan",
    faunaLatin: "Polyplectron Schleiermacheri",
    faunaEnglish: "Bornean Peacock Pheasant",
    cerita: "Taman Nasional Tanjung Puting suaka orangutan terbesar di dunia!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "kalsel",
    name: "Kalimantan Selatan",
    island: "Kalimantan",
    lat: -3.13,
    lng: 115.9,
    emoji: "🚣",
    capital: "Banjarbaru",
    rumahAdat: "Rumah Bubungan Tinggi",
    tarian: "Tari Baksa Kembang, Tari Radap Rahayu dan Tari Mantang Gandut",
    makanan: "Soto Banjar, Ketupat Kandangan dan Dodol Kandangan",
    alatMusik: "Panting, Kalampat, dan Sarunai",
    pakaianAdat: "Pakaian Adat Babaju Kun Galung Pacinan",
    tradisi: "Tari Baksa Kembang, Radap Rahayu, dan Mantang Gandut",
    senjataTradisional: "Keris Bujak Beliung dan Mandau",
    flora: "Kasturi",
    floraLatin: "Mangifera Casturi",
    floraEnglish: "Kalimantan Mango",
    fauna: "Kera Bekantan",
    faunaLatin: "Nasalis Larvatus",
    faunaEnglish: "Long-Nosed Monkey",
    cerita: "Pasar Terapung Lok Baintan berdagang tradisional di atas perahu!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "kaltim",
    name: "Kalimantan Timur",
    island: "Kalimantan",
    lat: 0.08,
    lng: 116.44,
    emoji: "🌴",
    capital: "Samarinda",
    rumahAdat: "Rumah Lamin, Rumah Betang dan Rumah Paser",
    tarian: "Tari Hudoq, Tari Hudoq Mahakam Ulu dan Tari Datun Ngentau",
    makanan: "Nasi Bekepor, Sayur Gangan Asam Kutai dan Sate Payau",
    alatMusik: "Sampe, Ketipung dan Jatung Adau",
    pakaianAdat: "Pakaian Adat Kustin",
    tradisi: "Tari Hudoq, Tari Kencet Lado dan Tari Ganjur",
    senjataTradisional: "Gayang, Tombak dan Mandau",
    flora: "Anggrek Hitam",
    floraLatin: "Coelogyne Pandurata",
    floraEnglish: "Black Orchid",
    fauna: "Pesut Mahakam",
    faunaLatin: "Orcaella Brevirostris",
    faunaEnglish: "Irrawaddy Dolphin",
    cerita: "Ibu Kota Nusantara baru dengan Hutan Hujan Tropis yang asri!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "kaltara",
    name: "Kalimantan Utara",
    island: "Kalimantan",
    lat: 2.76,
    lng: 116.27,
    emoji: "🐟",
    capital: "Tanjung Selor",
    rumahAdat: "Rumah Baloy",
    tarian: "Kancet Ledo dan Jepen",
    makanan: "Lawa",
    alatMusik: "Jatung Utang",
    pakaianAdat: "Pakaian Adat Ta’a dan Sapei Sapaq",
    tradisi: "Jugit Demaring. Jatung Utang dan Lalatip",
    senjataTradisional: "Mandau",
    flora: "Bakau",
    floraLatin: "Rhizophora Mangle",
    floraEnglish: "American Mangrove",
    fauna: "Gajah Borneo",
    faunaLatin: "Elephas Maximus Borneensis",
    faunaEnglish: "Borneo Pygmy Elephant",
    cerita: "Provinsi bungsu Kalimantan dengan kebudayaan suku Dayak Lundayeh!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "sulut",
    name: "Sulawesi Utara",
    island: "Sulawesi",
    lat: 2.93,
    lng: 125.13,
    emoji: "🐒",
    capital: "Manado",
    rumahAdat: "Rumah Walewangko",
    tarian: "Tari Kabasaran, Tari Maengket dan Tari Lenso Tatengesan",
    makanan: "Cakalang Fufu, Gohu Manado dan Tinutuan",
    alatMusik: "Kolintang, Salude dan Oli",
    pakaianAdat: "Pakaian Ikan Duyung, Baju Tatutu dan Walian Wangko",
    tradisi: "Kolintang dan Genre Oli",
    senjataTradisional: "Pedang Bara Sangihe, Peda, Tombak dan Perisai",
    flora: "Longusei",
    floraLatin: "Ficus Minahasae",
    floraEnglish: "Fig Tree",
    fauna: "Tangkasi",
    faunaLatin: "Tarsius Spectrum",
    faunaEnglish: "Tarsius",
    cerita: "Taman Laut Bunaken memiliki terumbu karang terindah di dunia!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "sulteng",
    name: "Sulawesi Tengah",
    island: "Sulawesi",
    lat: -1.13,
    lng: 121.8,
    emoji: "🗿",
    capital: "Palu",
    rumahAdat: "Rumah Tambi dan Rumah Souraja",
    tarian: "Tari Dopalak, Tari Raigo dan Tari Pamote",
    makanan: "Milu Siram, Palumara dan Kapurung",
    alatMusik: "Geso-Geso, Lalove dan Kakula Nuada",
    pakaianAdat: "Pakaian Adat Nggembe",
    tradisi: "Kakula Nuada, Tarian Dero dan tradisi Nggembe",
    senjataTradisional: "Guma, Pasatimpo dan Cakalele",
    flora: "Kayu Eboni",
    floraLatin: "Diospyros Celebica",
    floraEnglish: "Macassar Ebony",
    fauna: "Burung Maleo Senkawor/Panua",
    faunaLatin: "Macrocephalon Maleo",
    faunaEnglish: "Maleo Senkawor",
    cerita: "Lembah Bada menyimpan patung-patung batu purbakala misterius!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "sulsel",
    name: "Sulawesi Selatan",
    island: "Sulawesi",
    lat: -4.85,
    lng: 119.63,
    emoji: "⛵",
    capital: "Makassar",
    rumahAdat: "Rumah Adat Bugis, Rumah Tongkonan dan Rumah Mandar",
    tarian: "Tarian Bugis-Makassar dan Tarian Toraja",
    makanan: "Bolu Bandeng dan Sup Ikan",
    alatMusik: "Gendang dan Gong",
    pakaianAdat: "Baju Bodo, Baju Bella Dada dan Baju Labbu",
    tradisi: "Baju Bodo, Baju Pokko’ dan ritual Toraja seperti Rambu Solo’",
    senjataTradisional: "Badik, Gayang dan Keris Passatimpo",
    flora: "Pohon Buah Lontar",
    floraLatin: "Borassus Flabellifer",
    floraEnglish: "Palmyra Palm",
    fauna: "Burung Julang Sulawesi",
    faunaLatin: "Rhyticeros Cassidix / Aceros cassidix",
    faunaEnglish: "Knobbed Hornbill, Sulawesi Red-knobbed Hornbill",
    cerita: "Kapal layar kayu tradisional Pinisi buatan Bugis diakui dunia!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "sultra",
    name: "Sulawesi Tenggara",
    island: "Sulawesi",
    lat: -4.49,
    lng: 122.74,
    emoji: "🐴",
    capital: "Kendari",
    rumahAdat: "Rumah Malige, Rumah Mekongga dan Rumah Banua Tada",
    tarian: "Tarian Balumpa, Tari Dinggu dan Tari Lumense",
    makanan: "Lapa-lapa",
    alatMusik: "Ladolado",
    pakaianAdat: "Babu Nggawi, Pakaian Muna dan Pakaian Buton",
    tradisi: "Pakaian adat Tolaki, rumah adat Malige/Mekongga dan Tari Balumpa",
    senjataTradisional: "Keris dan Badik",
    flora: "Anggrek Serat",
    floraLatin: "Dendrobium Utile",
    floraEnglish: "Fibre Orchid",
    fauna: "Anoa Pegunungan",
    faunaLatin: "Bubalus Quarlesi",
    faunaEnglish: "Mountain Anoa",
    cerita: "Benteng Keraton Buton adalah benteng terluas di dunia versi Guiness Book!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "gorontalo",
    name: "Gorontalo",
    island: "Sulawesi",
    lat: 0.68,
    lng: 122.36,
    emoji: "🌾",
    capital: "Gorontalo",
    rumahAdat: "Rumah Adat Dulohupa, Rumah Adat Bantayo Poboide dan Rumah Adat Ma'lihe",
    tarian: "Tari Dana Dana, Tari Saronde dan Tari Biteya",
    makanan: "Sate Balanga, Binte Biluhuta dan Lalampa",
    alatMusik: "Wahulo, Polopalo, dan Gambusi",
    pakaianAdat: "Pakaian Adat Biliu dan Makuta",
    tradisi: "Binte Biluhuta",
    senjataTradisional: "Parang Aliyawo, Keris Baladu dan Tombak Totobu’o",
    flora: "Gofasa",
    floraLatin: "Vitex Cofassus",
    floraEnglish: "Bitti",
    fauna: "Ikan Bulalao",
    faunaLatin: "Planiliza Subviridis",
    faunaEnglish: "Dussumier Mullet",
    cerita: "Gorontalo tempat berkumpulnya Hiu Paus ramah di Teluk Tomini!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "sulbar",
    name: "Sulawesi Barat",
    island: "Sulawesi",
    lat: -2.21,
    lng: 118.47,
    emoji: "🌊",
    capital: "Mamuju",
    rumahAdat: "Rumah Boyang",
    tarian: "Tari Patuddu, Tari Bulu Londong dan Tari Sayyang Pattuqduq",
    makanan: "Jepa, Golla Kambu dan Ikan Terbang Asap",
    alatMusik: "Kecapi Mandar, Pompang dan Gongga Lima",
    pakaianAdat: "Pakaian Adat Pattuqduq Towaine",
    tradisi: "Saiyyang Pattuqduq",
    senjataTradisional: "Badik, Gayang dan Kandawulo",
    flora: "Cempaka Hutan Kasar",
    floraLatin: "Elmerrillia Ovalis",
    floraEnglish: "Magnolia Wood",
    fauna: "Burung Mandar Dengkur",
    faunaLatin: "Aramidopsis Plateni",
    faunaEnglish: "Snoring Rail, Celebes Rail, Platen's Rail",
    cerita: "Perahu cadik percadik tercepat suku Mandar melintasi samudra!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "maluku",
    name: "Maluku",
    island: "Maluku",
    lat: -5.54,
    lng: 130.32,
    emoji: "🌶️",
    capital: "Ambon",
    rumahAdat: "Rumah Baileo, Rumah Sasadu",
    tarian: "Tari Cakalele",
    makanan: "Papeda, Gohu Ikan dan Woku Komo-komo",
    alatMusik: "Tifa dan Totobuang",
    pakaianAdat: "Baju Cele, Baniang Putih dan Baju Koja",
    tradisi: "Tifa, Rumah Baileo",
    senjataTradisional: "Salawaku",
    flora: "Anggrek Larat",
    floraLatin: "Dendrobium Phalaenopsis",
    floraEnglish: "Cooktown Orchid",
    fauna: "Burung Nuri Raja Ambon",
    faunaLatin: "Alisterus Amboinensis",
    faunaEnglish: "Moluccan King-parrot, Ambon King Parrot",
    cerita: "Kepulauan Rempah sejarah Nusanatara yang harum legendaris!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "malut",
    name: "Maluku Utara",
    island: "Maluku",
    lat: 0.08,
    lng: 127.1,
    emoji: "🌋",
    capital: "Sofifi",
    rumahAdat: "Rumah Sasadu dan Rumah Baileo",
    tarian: "Tari Cakalele, Tari Bambu Gila dan Tari Soya‑Soya",
    makanan: "Papeda, Ikan Asar dan  Sambal Colo-Colo",
    alatMusik: "Arababu, Marakas dan Ukulele",
    pakaianAdat: "Baju Menteren Lamo dan Kimun Gia",
    tradisi: "Hibua Lamo, Tide-tide dan Soya-soya",
    senjataTradisional: "Sumpit, Badik dan Parang Salawaku",
    flora: "Cengkeh",
    floraLatin: "Syzygium Aromaticum",
    floraEnglish: "Clove",
    fauna: "Burung Bidadari Halmahera",
    faunaLatin: "Semioptera Wallacii",
    faunaEnglish: "Standardwing",
    cerita: "Rumah Kesultanan Ternate & Tidore berhiaskan Gunung Gamalama!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "papua",
    name: "Papua",
    island: "Papua",
    lat: -1.59,
    lng: 137.65,
    emoji: "🪶",
    capital: "Jayapura",
    rumahAdat: "Rumah Honai, Rumah Ebe'ai dan Rumah Kariwari",
    tarian: "Tari Perang, Tari Bakar Batu dan Tari Yospan",
    makanan: "Papeda dan ikan bakar khas pesisir Papua Barat",
    alatMusik: "Tifa",
    pakaianAdat: "Koteka/Holim, Rok Rumbai/Rumbia dan Pakaian Sali",
    tradisi: "Pakaian adat (koteka, Yokal, Sali, rok rumbai) dan Tradisi rumah adat (honai, ebe’ai)",
    senjataTradisional: "Parang, Kapak Batu dan Pisau Belati Tulang Kasuari",
    flora: "Matoa",
    floraLatin: "Pometia Pinnata",
    floraEnglish: "Fijian Longan",
    fauna: "Burung Cendrawasih 12 Kawat",
    faunaLatin: "Seleucidis Melanoleucus",
    faunaEnglish: "Twelve-wired Bird-of-paradise",
    cerita: "Rumah burung Burung Cendrawasih indah bermandikan sinar matahari!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "papuabarat",
    name: "Papua Barat",
    island: "Papua",
    lat: -2.52,
    lng: 133.46,
    emoji: "🐟",
    capital: "Manokwari",
    rumahAdat: "Rumah Honai, Rumah Ebe'ai dan Rumah Kaki Seribu Mod Aki Aksa",
    tarian: "Tari Yospan (Yosim Pancar), Tarian Perang&Ritual, Suling Tambur",
    makanan: "Papeda, Sagu Lempeng dan Udang Selingkuh",
    alatMusik: "Tifa, Suling Tambur dan Ukulele/Juk",
    pakaianAdat: "Koteka/Holim, Rok Rumbai/Rumbia dan Baju Kurung",
    tradisi: "Tari Yospan, Suling Tambur dan tradisi arsitektur Mod Aki Aksa (Rumah Kaki Seribu)",
    senjataTradisional: "Tombak, Kapak Batu dan Alat Tusuk Tulang Kuskus",
    flora: "Pisang Musa Ingens",
    floraLatin: "Musa ingens",
    floraEnglish: "Giant Banana",
    fauna: "Burung Cendrawasih Merah",
    faunaLatin: "Paradisaea rubra",
    faunaEnglish: "Red Bird-of-paradise",
    cerita: "Kepulauan Raja Ampat surga biodiversitas laut terlengkap di bumi!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "papuadaya",
    name: "Papua Barat Daya",
    island: "Papua",
    lat: -0.6,
    lng: 131.4,
    emoji: "🐢",
    capital: "Sorong",
    rumahAdat: "Rumah Honai dan Rumah Kaki Seribu Mod Aki Aksa",
    tarian: "Tari Selamat Datang dan Tari Yospan",
    makanan: "Papeda, Ikan Bakar Manokwari",
    alatMusik: "Guoto",
    pakaianAdat: "Koteka/Holim, Sali dan Ewer/Serui",
    tradisi: "Honai, Koteka dan Yokal",
    senjataTradisional: "Busur & Anak Panah, Tombak dan Pisau Belati",
    flora: "Buah Merah",
    floraLatin: "Pandanus Conoideus Lam",
    floraEnglish: "Red Fruit",
    fauna: "Kuskus Waigeo",
    faunaLatin: "Spilocuscus Papuensis",
    faunaEnglish: "Kuskus Scham-Scham",
    cerita: "Pintu masuk Raja Ampat & penyu raksasa Belimbing!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "papuatengah",
    name: "Papua Tengah",
    island: "Papua",
    lat: -3.71,
    lng: 136.47,
    emoji: "⛰️",
    capital: "Nabire",
    rumahAdat: "Rumah Honai, Rumah Ebe'ai dan Rumah Wamai",
    tarian: "Tari Perang (Highland Papua), Tari Aniri",
    makanan: "Papeda, Kue Sagu/Bagea, dan Sinole",
    alatMusik: "Tifa dan Suling Tambur",
    pakaianAdat: "Koteka/Holim, Rok Rumbai/Rumibia dan Baju Kurung",
    tradisi: "Noken",
    senjataTradisional: "Tombak (Tul//Mensa), Busur dan Panah (Fela), Pisau Belati Tulang Kasuari",
    flora: "Diplycosia Puradyatmikai",
    floraLatin: "Diplycosia puradyatmikai",
    floraEnglish: "Diplycosia puradyatmikai",
    fauna: "Burung Mambruk Selatan",
    faunaLatin: "Goura Scheepmakeri",
    faunaEnglish: "Southern Crowned Pigeon",
    cerita: "Puncak Carstensz Pyramide adalah puncak salju abadi di garis khatulistiwa!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "papuapegunungan",
    name: "Papua Pegunungan",
    island: "Papua",
    lat: -4.19,
    lng: 139.41,
    emoji: "🏔️",
    capital: "Jayawijaya",
    rumahAdat: "Rumah Honai, Rumah Ebe'ai dan Rumah Wamai",
    tarian: "Tari Perang Papua, Tari Aniri",
    makanan: "Papeda, Sate ulat sagu dan Bakar batu",
    alatMusik: "Tifa dan Suling Tambur",
    pakaianAdat: "Koteka/Holim, Rok Rumbai/Rumibia dan Baju Kurung",
    tradisi: "Noken, rumah Honai dan tarian perang",
    senjataTradisional: "Tombak (Tul/Mensa), Busur&Panah (Fela) dan Parang Jalowy",
    flora: "Woromo",
    floraLatin: "Pandanus Yilunea",
    floraEnglish: "Pandanus Yilunea",
    fauna: "Bakaga",
    faunaLatin: "Dendrolagus Mbaiso",
    faunaEnglish: "Dingiso",
    cerita: "Lembah Baliem tempat festival budaya tradisional suku Dani!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
  {
    id: "papuaselatan",
    name: "Papua Selatan",
    island: "Papua",
    lat: -6.83,
    lng: 139.26,
    emoji: "🌳",
    capital: "Merauke",
    rumahAdat: "Rumah Honai, Rumah Ebe'ai dan Rumah Suku Korowai",
    tarian: "Tari Perang, Tarian Bakar Batu dan Tari Suling Tambur",
    makanan: "Papeda, Sagu Bakar dan Lempeng Sagu",
    alatMusik: "Tifa dan Suling Tambur",
    pakaianAdat: "Koteka/Holim, Rok Rumbai/Rumbia dan Baju Kain Rumput",
    tradisi: "Koteka, Noken dan ukiran Asmat (Bisj Pole)",
    senjataTradisional: "Tombak (Tul/Mensa), Busur&Panah (Fela) dan Parang Jalowy",
    flora: "Matoa",
    floraLatin: "Pometia Pinnata",
    floraEnglish: "Fijian Longan",
    fauna: "Kanguru Kecil Wallaby",
    faunaLatin: "Dorcopsulus Macleayi",
    faunaEnglish: "Macleay's Dorcopsis",
    cerita: "Taman Nasional Wasur menyimpan istana rayap Musamus setinggi 5 meter!",
    counts: {"rumahAdat":4,"tarian":8,"musik":5,"kuliner":10,"cerita":7,"pakaian":4,"tradisi":6,"senjata":3,"flora":4,"fauna":4},
  },
];

export const islands = [
  "Sumatera",
  "Jawa",
  "Kalimantan",
  "Sulawesi",
  "Bali & Nusa Tenggara",
  "Maluku",
  "Papua",
] as const;

export const islandColors: Record<string, string> = {
  Sumatera: "#FF9A76",
  Jawa: "#7EC8E3",
  Kalimantan: "#A8D8B9",
  Sulawesi: "#FFD166",
  "Bali & Nusa Tenggara": "#C3A6FF",
  Maluku: "#6DD3CE",
  Papua: "#FF8B94",
};

// Darker accent colors for borders/strokes per island
export const islandStrokeColors: Record<string, string> = {
  Sumatera: "#E8734A",
  Jawa: "#5BA3C9",
  Kalimantan: "#7ABF9A",
  Sulawesi: "#E8B84A",
  "Bali & Nusa Tenggara": "#9B7FE6",
  Maluku: "#4ABAB5",
  Papua: "#E86B75",
};

// Fog/unexplored colors
export const fogColor = "#CBD5E1";
export const fogStrokeColor = "#94A3B8";
