/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PetaRouteImport } from './routes/peta'
import { Route as KuisRouteImport } from './routes/kuis'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProvinsiIdRouteImport } from './routes/provinsi.$id'

const PetaRoute = PetaRouteImport.update({
  id: '/peta',
  path: '/peta',
  getParentRoute: () => rootRouteImport,
} as any)
const KuisRoute = KuisRouteImport.update({
  id: '/kuis',
  path: '/kuis',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProvinsiIdRoute = ProvinsiIdRouteImport.update({
  id: '/provinsi/$id',
  path: '/provinsi/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/kuis': typeof KuisRoute
  '/peta': typeof PetaRoute
  '/provinsi/$id': typeof ProvinsiIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/kuis': typeof KuisRoute
  '/peta': typeof PetaRoute
  '/provinsi/$id': typeof ProvinsiIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/kuis': typeof KuisRoute
  '/peta': typeof PetaRoute
  '/provinsi/$id': typeof ProvinsiIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/kuis' | '/peta' | '/provinsi/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/kuis' | '/peta' | '/provinsi/$id'
  id: '__root__' | '/' | '/kuis' | '/peta' | '/provinsi/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  KuisRoute: typeof KuisRoute
  PetaRoute: typeof PetaRoute
  ProvinsiIdRoute: typeof ProvinsiIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/peta': {
      id: '/peta'
      path: '/peta'
      fullPath: '/peta'
      preLoaderRoute: typeof PetaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kuis': {
      id: '/kuis'
      path: '/kuis'
      fullPath: '/kuis'
      preLoaderRoute: typeof KuisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provinsi/$id': {
      id: '/provinsi/$id'
      path: '/provinsi/$id'
      fullPath: '/provinsi/$id'
      preLoaderRoute: typeof ProvinsiIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  KuisRoute: KuisRoute,
  PetaRoute: PetaRoute,
  ProvinsiIdRoute: ProvinsiIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
